feat: add telegram notifier
redstone-finance/redstone-oracle-monitoring pull request #16
Opened 2022-05-19 09:42 UTC by cehali

2022-05-19 23:04 UTC, hatskier requested changes
Let's change telegram report to smth like "Errors: 12, Warnings: 100". Later we can also add a link to more detailed report with UI.
Also, can you enable sending only critical notifications on telegram - only in case when there are errors (not only warnings)?

2022-05-19 23:04 UTC, hatskier commented on README.md
> +In order to integrate the monitoring notifier with telegram chat or channel, you need to populate `TELEGRAM_TOKEN` and `TELEGRAM_CHAT_ID` in the environment variables file. To get those variables you
`Chat id you can be found` -> `Chat id can be found`

2022-05-19 23:04 UTC, hatskier commented on src/helpers/db-connector.ts
> +export const disconnectFromRemoteMongo = async () => {
Why do we need to disconnect from DB?

2022-05-20 13:18 UTC, cehali commented on src/helpers/db-connector.ts
> +export const disconnectFromRemoteMongo = async () => {
I used it as a separate script, I will delete connect and disconnect to DB

2022-05-26 16:24 UTC, hatskier approved these changes

2022-05-27 08:45 UTC, merged